version: "3.8"
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: keycloak
    networks:
      - mysql
    restart: unless-stopped
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.0
    environment:
      KC_DB: mysql
      KC_DB_SCHEMA: keycloak
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "connectTimeout=30000"
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data/
    command:
      - "start-dev"
    networks:
      - mysql
    depends_on:
      - mysql
    restart: always
volumes:
  mysql_data:
  keycloak_data:
networks:
  mysql:
    driver: bridge
