#Server
server:
  port: 8030
  servlet:
    context-path: /orders
  error:
    include-message: always
#Management
management:
#  health:
#    circuitbreakers:
#      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
#Spring
spring:
  application:
    name: orders
  datasource:
    url: jdbc:mysql://localhost:3306/orders
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show_sql: true
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080/realms/marketx
#Eureka-Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

#feign:
#  circuitbreaker:
#    enabled: true
#resilience4j:
#  circuitbreaker:
#    instances:
#      product:
#        slidingWindowSize: 10                    #unit request
#        permittedNumberOfCallsInHalfOpenState: 5  #unit request
#        failureRateThreshold: 50                 #percent
#        waitDurationInOpenState: 10000           #10 seconds
#        registerHealthIndicator: true
#  timelimiter:
#    instances:
#      product:
#        timeoutDuration: 10s