#Server
server:
  port: 9090
  error:
    include-message: always
#Management
management:
#  health:
#    circuitbreakers:
#      enable: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
#Spring
spring:
  application:
    name: gateway
  cloud:
    gateway:
#      default-filters:
#        - TokenRelay
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/customer/**
          filters:
          - name: CircuitBreaker
            args:
              name: customer
              fallbackUri: forward:/fallback/customer
        - id: product
          uri: lb://PRODUCT
          predicates:
            - Path=/product/**
          filters:
          - name: CircuitBreaker
            args:
              name: product
              fallbackUri: forward:/fallback/product
        - id: orders
          uri: lb://ORDERS
          predicates:
            - Path=/orders/**
          filters:
          - name: CircuitBreaker
            args:
              name: orders
              fallbackUri: forward:/fallback/orders
#  security:
#    oauth2:
#      client:
#        registration:
#          keycloak-marketx-client:
#            provider: key-cloak-provider
#            client-id: keycloak-marketx-client
#            client-secret: ZWC6PE905oYqbTa8ajhNeWM2zXAaURyl
#            authorization-grant-type: authorization_code
#            redirect-uri: "http://localhost:9090/login/oauth2/code/keycloak-marketx-client"
#            scope: openid
#        provider:
#          key-cloak-provider:
#            issuer-uri: http://localhost:8080/realms/marketx
#Eureka-Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

