#Server
server:
  port: 9090
  error:
    include-message: always
#Management
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
#Spring
spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/customer/**
          filters:
          - name: CircuitBreaker
            args:
              name: customer
              fallbackUri: forward:/fallback/customer
        - id: product
          uri: lb://PRODUCT
          predicates:
            - Path=/product/**
          filters:
          - name: CircuitBreaker
            args:
              name: product
              fallbackUri: forward:/fallback/product
        - id: orders
          uri: lb://ORDERS
          predicates:
            - Path=/orders/**
          filters:
          - name: CircuitBreaker
            args:
              name: orders
              fallbackUri: forward:/fallback/orders
  security:
    oauth2:
      client:
        registration:
          marketx-gateway-client:
            provider: keycloak-provider
            client-id: marketx-client
            client-secret: 1WBfOo7UF8iR0vVJce6P60fgQrX2RWzJ
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9090/login/oauth2/code/keycloak-marketx
            scope: openid
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8080/realms/marketx
#Eureka-Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

resilience4j:
  circuitbreaker:
    instances:
      customer:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
      orders:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
      product:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED